# Azure DevOps Pipeline Configuration

trigger:
  branches:
    include:
      - main  # Trigger on commits to the main branch

pr:
  branches:
    include:
      - main  # Trigger on pull requests targeting the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu VM image

steps:
- checkout: self  # Check out the repository code

- task: UseDotNet@2  # Install the .NET SDK
  inputs:
    packageType: 'sdk'  # Specify that we want to install the SDK
    version: '8.x'  # Install the latest 8.x version of the SDK
    installationPath: $(Agent.ToolsDirectory)/dotnet  # Set the installation path

- script: dotnet restore  # Restore project dependencies
  displayName: 'Restore dependencies'

- script: dotnet build --no-restore  # Build the project without restoring dependencies
  displayName: 'Build'

- script: dotnet test --no-build --verbosity normal  # Run tests without building
  displayName: 'Test'
